# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- group: VsCodeDeploy
- group: IntegrationTest

trigger:
  branches:
    include:
      - dev
      - master

pr:
  branches:
    include:
      - dev

stages: 
- stage: test
  jobs:
    - job: testWin
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '8.x'
          displayName: 'Install Node.js'
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]cn-$v.vsix"' # Required when targetType == Inline
        - task: Bash@3
          inputs:
            targetType: inline
            script: 'npm install && npm run test --instanceName=$(instanceName) --username=$(UserName) --password=$(password)' # Required when targetType == Inline
    - job: testMac
      pool:
        vmImage: 'macOS-latest'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '8.x'
          displayName: 'Install Node.js'
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]cn-$v.vsix"' # Required when targetType == Inline
        - task: Bash@3
          inputs:
            targetType: inline
            script: 'npm install && npm run test --instanceName=$(instanceName) --username=$(UserName) --password=$(password)' # Required when targetType == Inline
    - job: testUbuntu
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '8.x'
          displayName: 'Install Node.js'
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]cn-$v.vsix"' # Required when targetType == Inline
        - task: Bash@3
          inputs:
            targetType: inline
            script: 'npm install && npm run test --instanceName=$(instanceName) --username=$(UserName) --password=$(password)' # Required when targetType == Inline
- stage: "deploy"
  dependsOn: test
#Build from dev
  jobs: 
    - job: PackageVsix
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
      pool:
        vmImage: 'vs2017-win2016'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '8.x'
          displayName: 'Install Node.js'
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]cn-$v.vsix"' # Required when targetType == Inline
        - task: Bash@3
          inputs:
            targetType: inline
            script: 'npm install && npm install -g vsce && vsce package' # Required when targetType == Inline
        - task: PublishPipelineArtifact@0
          inputs:
            artifactName: "$(vsix)"
            targetPath: "./$(vsix)"
  #publish from master
    - job: PublishMarketPlace 
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      pool:
        vmImage: 'vs2017-win2016'
      steps:
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: '. .\buildfunctions.ps1; $v = addBuildNumber -buildNumber $(Build.BuildNumber);write-host "##vso[task.setvariable variable=vsix]cn-$v.vsix"' # Required when targetType == Inline
        - task: NodeTool@0
          inputs:
            versionSpec: '8.x'
          displayName: 'Install Node.js'
        - script: |
            npm install
          displayName: 'npm install'
        - task: Bash@3
          inputs:
            targetType: inline
            script: 'npm install && npm install -g vsce && vsce publish -p $(ambsKey)' # Required when targetType == Inline